INT_SIZE = 4
INDEX_ENTRIES_PER_PAGE = 1
INDEX_ENTRY_SIZE = 8
DATA_RECORDS_PER_PAGE = 4
DATA_RECORD_SIZE = 16 * INT_SIZE  # 16 = 1 key + 15 numbers
BYTE_ORDER = "big"
MAX_INT = 2147483647
INDEX_RECORD_SIZE = (3 * INT_SIZE) + INT_SIZE
DATA_RECORD_LENGTH = 15

